# https://docs.getdbt.com/docs/core/connect-data-platform/postgres-setup

config:
  send_anonymous_usage_stats: false

dbt_project:
  target: dev
  outputs:
    dev:
      type: &type postgres
      host: &host "{{ env_var('POSTGRES_HOST') }}"
      user: &user "{{ env_var('POSTGRES_USER') }}"
      password: &password "{{ env_var('POSTGRES_PASSWORD') }}"
      port: &port 5432
      dbname: air_quality
      schema: dbt
      threads: 1
      connect_timeout: 10 # default 10 seconds
